USE_LR_PARSER

prog


(* ======================================================================================================= *)
<Program>           ::= <StatementList>       .                                                            
<StatementList>     ::= <Statement> ";" <StatementList>
                      |<Epsilon> .
<Epsilon>           ::= .
<Statement>         ::= <Declaration> ";"
                      | <Assignment> ";"
                      | <PrintSt> ";"
                      | <Block>
                      | <ForLoop>
                      | <ConditionStatement>
                      | <WhileLoop>
                      | <Increment> ";" .
<Declaration>       ::= "INTEGER" Variable
                      | "BOOLEAN" Variable .
<Assignment>        ::= Variable "=" <Expression>                                       
                      | "INTEGER" Variable "=" <Expression>
                      | "BOOLEAN" Variable "=" <Expression>                                 .
<PrintSt>               ::= "print" "("<Expr>")". 
<Block>                 ::= "{"<StatementList>"}".
<CondStatement>         ::= "if" "("<Expr>")" "then" <Block>
                        |"if" "("<Expr>")" "then" <Block> "else" <Block>.
<WhileLoop>             ::= "while" "("<Expr>")" <Block>.
<ForLoop>               ::= "for" "(" <Assignment> ";" <Expr> ";" <Increment> ";" ")" <Block>.
<Increment>             ::= "++" Variable
                        | Variable "++"
                        | "--" Variable
                        | Variable "--".
<Expr>                  ::= <Expr> "||" <AndExpr>
                        | <AndExpr> .
<AndExpr>               ::= <AndExpr> "&&" <EqualityExpr> 
                        |<EqualityExpr>.
<EqualityExpr>          ::= <EqualityExpr> "!=" <ComparisonExpr>
                        |<EqualityExpr> "==" <ComparisonExpr>
                        |<ComparisonExpr>.
<ComaprisonExpr>        ::= <ComparisonExpr> "<" <AddSubExpr>
                        |<ComparisonExpr> ">" <AddSubExpr>
                        |<ComparisonExpr>.
<AddSubExpr>            ::= <AddSubExpr> "+" <MultiDivModExpr>
                        |<AddSubExpr> "-" <MultiDivModExpr>
                        |<MultiDivModExpr>.
<MultiDivModExpr>       ::=<MultiDivModExpr> "*" <UnaryExpr>
                        |<MultiDivModExpr> "DIV" <UnaryExpr>
                        |<MultiDivModExpr> "MOD" <UnaryExpr>
                        |<UnaryExpr>.
<UnaryExpr>             ::= "!" <UnaryExpr>
                        | "-" <ExpExpr>
                        | <ExpExpr>.
<ExprExp>           ::= <ExprBase> "^" <ExprExp> 
                      | <ExprBase>                                                          .
<ExprBase>          ::= Integer 
                      | "true" 
                      | "false" 
                      | Variable 
                      | "(" <Expression> ")" 
                      | "|"<Expression>"|" 
                      | <Increment> 



                       